const calendarContent = [
    { day: 1, type: 'image', url: './assets/images/card 1.png', title: 'December 1' },
    { day: 2, type: 'image', url: './assets/images/card 2.png', title: 'December 2' },
    { day: 3, type: 'image', url: './assets/images/card 3.png', title: 'December 3' },
    { day: 4, type: 'gif', url: './assets/images/card 4.gif', title: 'December 4' },
    { day: 5, type: 'image', url: './assets/images/card 5.png', title: 'December 5' },
    { day: 6, type: 'image', url: './assets/images/card 6.png', title: 'December 6', link: 'https://www.youtube.com/watch?v=A-er_AJioOA' },
    { day: 7, type: 'image', url: './assets/images/card 7.png', title: 'December 7' },
    { day: 8, type: 'gif', url: './assets/images/card 8.gif', title: 'December 8' },
    { day: 9, type: 'image', url: './assets/images/card 9.png', title: 'December 9', link: 'https://open.spotify.com/track/3e18zWToEVj78u6sfr6872?si=709c9fcbc1004119' },
    { day: 10, type: 'gif', url: './assets/images/card 10.gif', title: 'December 10' },
    { day: 11, type: 'image', url: './assets/images/card 11.png', title: 'December 11' },
    { day: 12, type: 'image', url: './assets/images/card 12.png', title: 'December 12' },
    { day: 13, type: 'image', url: './assets/images/card 13.png', title: 'December 13', link: 'https://www.whychristmas.com/fun/wordle' },
    { day: 14, type: 'image', url: './assets/images/card 14.png', title: 'December 14' },
    { day: 15, type: 'image', url: './assets/images/card 15.png', title: 'December 15' },
    { day: 16, type: 'image', url: './assets/images/card 16.png', title: 'December 16' },
    { day: 17, type: 'image', url: './assets/images/card 17.png', title: 'December 17', link: 'https://www.youtube.com/watch?v=4I5mkkoDxUM' },
    { day: 18, type: 'image', url: './assets/images/card 18.png', title: 'December 18' },
    { day: 19, type: 'image', url: './assets/images/card 19.png', title: 'December 19' },
    { day: 20, type: 'image', url: './assets/images/card 20.png', title: 'December 20', link: 'https://www.cattennisgame.com/' },
    { day: 21, type: 'image', url: './assets/images/card 21.png', title: 'December 21' },
    { day: 22, type: 'image', url: './assets/images/card 22.png', title: 'December 22' },
    { day: 23, type: 'image', url: './assets/images/card 23.png', title: 'December 23' },
    { day: 24, type: 'image', url: './assets/images/card 24.png', title: 'December 24' }
];
